#!/bin/bash

clear
cd /root
cp led-hg/inet-hg680p.sh /usr/bin/
cp led-hg/hg680p.sh /usr/bin/
chmod +x /usr/bin/inet-hg680p.sh
chmod +x /usr/bin/hg680p.sh

cd /root
touch /root/led
echo ok > /root/led
echo " Install selesai"
echo " ketik perintah : inet-hg680p.sh -s"
echo " Untuk stop LED Indicator"
sleep 2
bash inet-hg680p.sh -r
